# Site settings
baseurl: ''
url: "https://defeo.lu"
permalink: /blog/:categories/:title

# About
authors:
  - name: Luca De Feo
    url: 'https://defeo.lu/'
created: 2019
license:
  name: Creative Commons 4.0 Attribution-ShareAlike
  shortname: CC-BY-SA 4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/
  badge: https://i.creativecommons.org/l/by-sa/4.0/80x15.png
mastodon_server: ioc.exchange
mastodon_username: luca_defeo
twitter_username: luca_defeo
github_username:  defeo

# Build settings
markdown: kramdown
#theme: minima
kramdown:
  parse_block_html: true

# Page defaults
defaults:
  - scope:
      path: ""
    values:
      title: Luca De Feo
      description: >-
        Luca De Feo is a researcher at IBM. He works on Post-quantum
        Cryptography, Isogeny-based Cryptography, Algorithmic Number
        Theory and Computer Algebra.
